FROM node:20-alpine

# 보안: non-root user 사용
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001

WORKDIR /home/node/app

COPY --chown=nodejs:nodejs package*.json ./

RUN npm install

COPY --chown=nodejs:nodejs . .

USER nodejs

EXPOSE $PORT

CMD [ "node", "src/index.js" ]